export const PART_LIST_REQUEST = 'PART_LIST_REQUEST'
export const PART_LIST_SUCCESS = 'PART_LIST_SUCCESS'
export const PART_LIST_FAIL = 'PART_LIST_FAIL'

export const PART_DETAILS_REQUEST = 'PART_DETAILS_REQUEST'
export const PART_DETAILS_SUCCESS = 'PART_DETAILS_SUCCESS'
export const PART_DETAILS_FAIL = 'PART_DETAILS_FAIL'